version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
  disable_publish_on_pr: false
build_script:
- ps: >-
    if($env:APPVEYOR_BUILD_VERSION -match "(\d+\.\d+\.\d+)(.*)") {
       $version = $Matches[1]
       $prefix = $Matches[2]
    }



    dotnet restore

    dotnet build -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION

    dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION --include-symbols
test_script:
- ps: '#dotnet test -xml test.xml'
artifacts:
- path: PRI.DICore\bin\Release\*.nupkg
- path: PRI.DICore.SystemNetHttp\bin\Release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  on:
    branch: master
