//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// Default implementation of <sealso cref="IHttpContentHeaders" />
    /// </summary>
    public sealed partial class HttpContentHeaders : IHttpContentHeaders
    {
        
        private System.Net.Http.Headers.HttpContentHeaders containedObject;
        
        public HttpContentHeaders(System.Net.Http.Headers.HttpContentHeaders containedObject)
        {
            if ((containedObject == null))
            {
                throw new System.ArgumentNullException("containedObject");
            }
            this.containedObject = containedObject;
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.Allow"/>
        /// </summary>
        public System.Collections.Generic.ICollection<string> Allow
        {
            get
            {
                return this.containedObject.Allow;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentDisposition"/>
        /// </summary>
        public System.Net.Http.Headers.ContentDispositionHeaderValue ContentDisposition
        {
            get
            {
                return this.containedObject.ContentDisposition;
            }
            set
            {
                this.containedObject.ContentDisposition = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentEncoding"/>
        /// </summary>
        public System.Collections.Generic.ICollection<string> ContentEncoding
        {
            get
            {
                return this.containedObject.ContentEncoding;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentLanguage"/>
        /// </summary>
        public System.Collections.Generic.ICollection<string> ContentLanguage
        {
            get
            {
                return this.containedObject.ContentLanguage;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentLength"/>
        /// </summary>
        public System.Nullable<long> ContentLength
        {
            get
            {
                return this.containedObject.ContentLength;
            }
            set
            {
                this.containedObject.ContentLength = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentLocation"/>
        /// </summary>
        public System.Uri ContentLocation
        {
            get
            {
                return this.containedObject.ContentLocation;
            }
            set
            {
                this.containedObject.ContentLocation = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentMD5"/>
        /// </summary>
        public byte[] ContentMD5
        {
            get
            {
                return this.containedObject.ContentMD5;
            }
            set
            {
                this.containedObject.ContentMD5 = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentRange"/>
        /// </summary>
        public System.Net.Http.Headers.ContentRangeHeaderValue ContentRange
        {
            get
            {
                return this.containedObject.ContentRange;
            }
            set
            {
                this.containedObject.ContentRange = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.ContentType"/>
        /// </summary>
        public System.Net.Http.Headers.MediaTypeHeaderValue ContentType
        {
            get
            {
                return this.containedObject.ContentType;
            }
            set
            {
                this.containedObject.ContentType = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.Expires"/>
        /// </summary>
        public System.Nullable<System.DateTimeOffset> Expires
        {
            get
            {
                return this.containedObject.Expires;
            }
            set
            {
                this.containedObject.Expires = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.LastModified"/>
        /// </summary>
        public System.Nullable<System.DateTimeOffset> LastModified
        {
            get
            {
                return this.containedObject.LastModified;
            }
            set
            {
                this.containedObject.LastModified = value;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.System.Collections.IEnumerable.GetEnumerator"/>
        /// </summary>
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return ((System.Collections.IEnumerable)(this.containedObject)).GetEnumerator();
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.HttpContentHeaders.GetEnumerator"/>
        /// </summary>
        public System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.IEnumerable<string>>> GetEnumerator()
        {
            return this.containedObject.GetEnumerator();
        }
    }
}
