//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// Default implementation of <sealso cref="IHttpMessageInvoker" />
    /// </summary>
    public sealed partial class HttpMessageInvoker : IHttpMessageInvoker
    {
        
        private System.Net.Http.HttpMessageInvoker containedObject;
        
        public HttpMessageInvoker(System.Net.Http.HttpMessageInvoker containedObject)
        {
            if ((containedObject == null))
            {
                throw new System.ArgumentNullException("containedObject");
            }
            this.containedObject = containedObject;
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.HttpMessageInvoker.SendAsync"/>
        /// </summary>
        public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            return this.containedObject.SendAsync(request, cancellationToken);
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.HttpMessageInvoker.Dispose"/>
        /// </summary>
        public void Dispose()
        {
            this.containedObject.Dispose();
        }
    }
}
