//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// An interface to model an abstraction of <see cref="System.Net.Http.Headers.ContentRangeHeaderValue" />
    /// </summary>
    public interface IContentRangeHeaderValue : System.ICloneable
    {
        
        string Unit
        {
            get;
            set;
        }
        
        System.Nullable<long> From
        {
            get;
        }
        
        System.Nullable<long> To
        {
            get;
        }
        
        System.Nullable<long> Length
        {
            get;
        }
        
        bool HasLength
        {
            get;
        }
        
        bool HasRange
        {
            get;
        }
        
        bool Equals(object obj);
        
        int GetHashCode();
        
        string ToString();
    }
}
