//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{


	/// <summary>
	/// An interface to model an abstraction of <see cref="System.Net.Http.HttpRequestMessage" />
	/// </summary>
	public interface IHttpRequestMessage : System.IDisposable
	{

		System.Version Version
		{
			get;
			set;
		}

		System.Net.Http.HttpContent Content
		{
			get;
			set;
		}

		System.Net.Http.HttpMethod Method
		{
			get;
			set;
		}

		System.Uri RequestUri
		{
			get;
			set;
		}

		System.Net.Http.Headers.HttpRequestHeaders Headers
		{
			get;
		}

		System.Collections.Generic.IDictionary<string, object> Properties
		{
			get;
		}

		string ToString();
	}
}
