//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// An interface to model an abstraction of <see cref="System.Net.Http.HttpResponseMessage" />
    /// </summary>
    public interface IHttpResponseMessage : System.IDisposable
    {
        
        System.Version Version
        {
            get;
            set;
        }
        
        System.Net.Http.HttpContent Content
        {
            get;
            set;
        }
        
        System.Net.HttpStatusCode StatusCode
        {
            get;
            set;
        }
        
        string ReasonPhrase
        {
            get;
            set;
        }
        
        System.Net.Http.Headers.HttpResponseHeaders Headers
        {
            get;
        }
        
        System.Net.Http.HttpRequestMessage RequestMessage
        {
            get;
            set;
        }
        
        bool IsSuccessStatusCode
        {
            get;
        }
        
        System.Net.Http.HttpResponseMessage EnsureSuccessStatusCode();
        
        string ToString();
    }
}
