//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{


	/// <summary>
	/// An interface to model an abstraction of <see cref="System.Net.Http.MultipartFormDataContent" />
	/// </summary>
	public interface IMultipartFormDataContent : System.IDisposable, System.Collections.Generic.IEnumerable<System.Net.Http.HttpContent>, System.Collections.IEnumerable
	{

		void Add(System.Net.Http.HttpContent content);

		void Add(System.Net.Http.HttpContent content, string name);

		void Add(System.Net.Http.HttpContent content, string name, string fileName);
	}
}
