//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// Default implementation of <sealso cref="IMultipartFormDataContent" />
    /// </summary>
    public sealed partial class MultipartFormDataContent : IMultipartFormDataContent
    {
        
        private System.Net.Http.MultipartFormDataContent containedObject;
        
        public MultipartFormDataContent(System.Net.Http.MultipartFormDataContent containedObject)
        {
            if ((containedObject == null))
            {
                throw new System.ArgumentNullException("containedObject");
            }
            this.containedObject = containedObject;
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.MultipartFormDataContent.Add"/>
        /// </summary>
        public void Add(System.Net.Http.HttpContent content)
        {
            this.containedObject.Add(content);
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.MultipartFormDataContent.Add"/>
        /// </summary>
        public void Add(System.Net.Http.HttpContent content, string name)
        {
            this.containedObject.Add(content, name);
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.MultipartFormDataContent.Add"/>
        /// </summary>
        public void Add(System.Net.Http.HttpContent content, string name, string fileName)
        {
            this.containedObject.Add(content, name, fileName);
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.MultipartFormDataContent.System.Collections.IEnumerable.GetEnumerator"/>
        /// </summary>
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return ((System.Collections.IEnumerable)(this.containedObject)).GetEnumerator();
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.MultipartFormDataContent.Dispose"/>
        /// </summary>
        public void Dispose()
        {
            this.containedObject.Dispose();
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.MultipartFormDataContent.GetEnumerator"/>
        /// </summary>
        public System.Collections.Generic.IEnumerator<System.Net.Http.HttpContent> GetEnumerator()
        {
            return this.containedObject.GetEnumerator();
        }
    }
}
