//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// Default implementation of <sealso cref="IProductHeaderValue" />
    /// </summary>
    public sealed partial class ProductHeaderValue : IProductHeaderValue
    {
        
        private System.Net.Http.Headers.ProductHeaderValue containedObject;
        
        public ProductHeaderValue(System.Net.Http.Headers.ProductHeaderValue containedObject)
        {
            if ((containedObject == null))
            {
                throw new System.ArgumentNullException("containedObject");
            }
            this.containedObject = containedObject;
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.ProductHeaderValue.Name"/>
        /// </summary>
        public string Name
        {
            get
            {
                return this.containedObject.Name;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.ProductHeaderValue.Version"/>
        /// </summary>
        public string Version
        {
            get
            {
                return this.containedObject.Version;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.ProductHeaderValue.ToString"/>
        /// </summary>
        public override string ToString()
        {
            return this.containedObject.ToString();
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.ProductHeaderValue.Equals"/>
        /// </summary>
        public override bool Equals(object obj)
        {
            return this.containedObject.Equals(obj);
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.ProductHeaderValue.GetHashCode"/>
        /// </summary>
        public override int GetHashCode()
        {
            return this.containedObject.GetHashCode();
        }
    }
}
