//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace PRI.DICore.SystemNetHttp
{
    
    
    /// <summary>
    /// Default implementation of <sealso cref="IRangeItemHeaderValue" />
    /// </summary>
    public sealed partial class RangeItemHeaderValue : IRangeItemHeaderValue
    {
        
        private System.Net.Http.Headers.RangeItemHeaderValue containedObject;
        
        public RangeItemHeaderValue(System.Net.Http.Headers.RangeItemHeaderValue containedObject)
        {
            if ((containedObject == null))
            {
                throw new System.ArgumentNullException("containedObject");
            }
            this.containedObject = containedObject;
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.RangeItemHeaderValue.From"/>
        /// </summary>
        public System.Nullable<long> From
        {
            get
            {
                return this.containedObject.From;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.RangeItemHeaderValue.To"/>
        /// </summary>
        public System.Nullable<long> To
        {
            get
            {
                return this.containedObject.To;
            }
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.RangeItemHeaderValue.ToString"/>
        /// </summary>
        public override string ToString()
        {
            return this.containedObject.ToString();
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.RangeItemHeaderValue.Equals"/>
        /// </summary>
        public override bool Equals(object obj)
        {
            return this.containedObject.Equals(obj);
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.RangeItemHeaderValue.GetHashCode"/>
        /// </summary>
        public override int GetHashCode()
        {
            return this.containedObject.GetHashCode();
        }
        
        /// <summary>
        /// <see cref="System.Net.Http.Headers.RangeItemHeaderValue.System.ICloneable.Clone"/>
        /// </summary>
        object System.ICloneable.Clone()
        {
            return ((System.ICloneable)(this.containedObject)).Clone();
        }
    }
}
